diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=David Huang
user.email=educm199@gmail.com
user.signingkey=null
core.editor=code --wait
core.edior=code --wait
core.autocrlf=true
core.longpaths=true
gpg.program=gpg1
commit.gpgsign=true
tag.forcesignannotated=null
pull.ff=only
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/DavidHuangz/AR_TREE.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.VirtualMode.remote=origin
branch.VirtualMode.merge=refs/heads/VirtualMode
lfs.https://github.com/DavidHuangz/AR_TREE.git/info/lfs.access=basic
branch.AppleAR.remote=origin
branch.AppleAR.merge=refs/heads/AppleAR
branch.playstore.remote=origin
branch.playstore.merge=refs/heads/playstore
lfs.repositoryformatversion=0
